package com.ht.stream.proxy

import android.content.Context
import com.ht.stream.data.MockRule
import com.ht.stream.data.MockStore
import com.ht.stream.data.RequestStore
import com.ht.stream.ui.decompressBody
import org.json.JSONArray
import org.json.JSONObject
import org.json.JSONTokener

/**
 * 接口模拟引擎：在代理层判定「这条请求是否要返回模拟响应」，并生成响应内容。
 *
 * 命中条件（全部满足）：
 *  1. 总开关开启，且发起请求的应用在「接口模拟」设置页被单独开启；
 *  2. 存在一条 enabled 的规则，其 method / host / path 与请求匹配（按配置顺序取第一条）。
 *
 * 响应示例：规则配置了 body 就用配置的；没配置则按「接口响应数据类型」自动生成——
 * 优先取本机抓到的同接口历史响应作为样本，按类型生成结构一致的占位示例
 * （JSON → 保留键结构、值按类型置空；XML/HTML → 类型化骨架；文本 → 占位文本）。
 */
object MockEngine {

    data class MockResponse(
        val statusCode: Int,
        val statusText: String,
        val headers: List<Pair<String, String>>,
        val body: ByteArray,
        /** true = 响应体是按类型自动生成的示例（规则未配置示例） */
        val autoGenerated: Boolean
    )

    /** 匹配规则；无命中返回 null */
    fun match(context: Context, uid: Int, method: String, host: String, path: String): MockRule? {
        if (!MockStore.isUidMocked(context, uid)) return null
        val hits = MockStore.rules(context).filter { rule ->
            rule.enabled &&
                methodMatches(rule.method, method) &&
                hostMatches(rule.host, host) &&
                pathMatches(rule.path, path)
        }
        if (hits.isEmpty()) return null
        // 更具体的规则优先：精确 path > 通配 path > 未配置 path。
        // 否则一条 host 级的「/」或空 path 规则会把同 host 下的明细接口全部吞掉。
        return hits.maxByOrNull { specificity(it.path) }
    }

    /** path 具体度：精确路径 2、含通配 1、空/全匹配 0；同级按字面长度更长者优先 */
    private fun specificity(path: String): Int {
        val p = path.trim()
        return when {
            p.isEmpty() || p == "*" -> 0
            p.contains('*') -> 1_000 + p.length
            else -> 1_000_000 + p.length
        }
    }

    /** 构造完整响应（含延迟与自定义头） */
    fun respond(context: Context, rule: MockRule, method: String, host: String, path: String): MockResponse {
        if (rule.delayMs > 0) {
            runCatching { Thread.sleep(rule.delayMs.coerceAtMost(30_000L)) }
        }
        val custom = rule.body.isNotBlank()
        val bytes = if (custom) {
            rule.body.toByteArray(Charsets.UTF_8)
        } else {
            generateSample(context, rule.contentType, method, host, path)
        }
        val headers = buildList {
            add("Content-Type" to rule.contentType)
            addAll(rule.headers.filter { (k, _) ->
                !k.equals("Content-Length", true) && !k.equals("Connection", true) &&
                    !k.equals("Transfer-Encoding", true)
            })
        }
        return MockResponse(
            statusCode = rule.statusCode.takeIf { it in 100..599 } ?: 200,
            statusText = statusTextOf(rule.statusCode),
            headers = headers,
            body = bytes,
            autoGenerated = !custom
        )
    }

    /**
     * 是否存在针对该 host 的模拟规则。用于强制解密：
     * 即使「抓包模式」白/黑名单排除了该 host，只要有模拟规则也要 MITM，否则看不到请求就无法模拟。
     */
    internal fun shouldForceMitm(context: Context, host: String): Boolean {
        if (!MockStore.isEnabled(context)) return false
        return MockStore.rules(context).any { it.enabled && hostMatches(it.host, host) }
    }

    // ================= 匹配 =================

    private fun methodMatches(rule: String, actual: String): Boolean {
        val r = rule.trim()
        return r.isEmpty() || r == "*" || r.equals(actual, true)
    }

    /** host 支持 *.example.com / .example.com 通配子域；空=不限 */
    internal fun hostMatches(rule: String, actual: String): Boolean {
        val r = rule.trim().lowercase()
        if (r.isEmpty() || r == "*") return true
        val h = actual.lowercase()
        val target = h.substringBefore(':')
        return when {
            r.startsWith("*.") -> target == r.substring(2) || target.endsWith(r.substring(1))
            r.startsWith(".") -> target.endsWith(r)
            else -> target == r
        }
    }

    /** path 支持 * 通配；无 * 时按「完全相同」或「前缀 + /」匹配（自动忽略 query）。
     *  注意 "/" 只匹配根路径本身，不会吞掉该 host 下其它接口——"不限 path" 请留空或填 * */
    private fun pathMatches(rule: String, actual: String): Boolean {
        val r = rule.trim()
        if (r.isEmpty() || r == "*") return true
        val p = actual.substringBefore('?')
        if (r.contains('*')) return wildcardMatch(r, p)
        if (p == r) return true
        if (r == "/") return false
        return p.startsWith("$r/") || (r.endsWith("/") && p.startsWith(r))
    }

    /** 简易 glob：* 匹配任意字符序列 */
    private fun wildcardMatch(pattern: String, text: String): Boolean {
        val parts = pattern.split('*')
        if (parts.size == 1) return pattern == text
        var idx = 0
        for ((i, part) in parts.withIndex()) {
            if (part.isEmpty()) continue
            val found = text.indexOf(part, idx)
            if (found < 0) return false
            // 模式不以 * 开头时，第一段必须落在最前面
            if (i == 0 && found != 0) return false
            idx = found + part.length
        }
        val last = parts.last()
        return pattern.endsWith("*") || last.isEmpty() || text.endsWith(last)
    }

    // ================= 示例生成 =================

    /**
     * 按响应数据类型自动生成示例。
     * 优先用本机抓到的同接口历史响应作为「结构样本」，再去掉具体值只留类型骨架。
     */
    fun generateSample(context: Context, contentType: String, method: String, host: String, path: String): ByteArray {
        val ct = contentType.lowercase()
        val template = capturedResponse(context, method, host, path)
        val text = template?.let { runCatching { String(it, Charsets.UTF_8).trim() }.getOrNull() }

        if (!text.isNullOrEmpty()) {
            jsonSample(text)?.let { return it.toByteArray(Charsets.UTF_8) }
            if (text.startsWith("<")) return markupSample(text, ct).toByteArray(Charsets.UTF_8)
            if (isMostlyText(text) && !ct.contains("octet-stream")) {
                return text.take(2048).toByteArray(Charsets.UTF_8)
            }
        }
        return defaultSample(ct).toByteArray(Charsets.UTF_8)
    }

    /** 取最近一条同 method+host+path 且响应体非空的抓包记录（已按 Content-Encoding 解压） */
    private fun capturedResponse(context: Context, method: String, host: String, path: String): ByteArray? {
        val target = path.substringBefore('?')
        val hit = RequestStore.exchanges.value.firstOrNull { e ->
            e.responseBody.isNotEmpty() &&
                e.method.equals(method, true) &&
                e.host.equals(host, true) &&
                e.path.substringBefore('?') == target
        } ?: return null
        val enc = hit.headerValue(hit.responseHeaders, "Content-Encoding")
        return decompressBody(enc, hit.responseBody) ?: hit.responseBody
    }

    /** JSON → 保留键结构，值按数据类型置为占位（字符串空、数字 0、布尔 false） */
    private fun jsonSample(text: String): String? {
        val v = runCatching { JSONTokener(text).nextValue() }.getOrNull()
        if (v !is JSONObject && v !is JSONArray) return null
        return runCatching { placeholder(v).toString() }.getOrNull()
    }

    private fun placeholder(v: Any?): Any = when (v) {
        is JSONObject -> JSONObject().apply {
            v.keys().forEach { k -> put(k, placeholder(v.opt(k))) }
        }
        is JSONArray -> JSONArray().apply {
            for (i in 0 until minOf(v.length(), 3)) put(placeholder(v.opt(i)))
        }
        is String -> ""
        is Boolean -> false
        is Int, is Long -> 0
        is Double, is Float -> 0
        else -> JSONObject.NULL
    }

    /** XML / HTML → 保留根标签与同级标签名，内容置空 */
    private fun markupSample(text: String, contentType: String): String {
        val tags = Regex("<([A-Za-z_][\\w:.-]*)").findAll(text)
            .map { it.groupValues[1] }
            .filterNot { it.startsWith("?") }
            .distinct()
            .take(8)
            .toList()
        if (tags.isEmpty()) return defaultSample(contentType)
        val root = tags.first()
        val children = tags.drop(1)
        val body = if (children.isEmpty()) "" else children.joinToString("") { "<$it></$it>" }
        return "<?xml version=\"1.0\" encoding=\"UTF-8\"?><$root>$body</$root>"
    }

    private fun defaultSample(contentType: String): String = when {
        contentType.contains("json") ->
            """{"code":0,"message":"mock","data":{}}"""
        contentType.contains("xml") ->
            """<?xml version="1.0" encoding="UTF-8"?><response><code>0</code><message>mock</message></response>"""
        contentType.contains("html") ->
            "<!DOCTYPE html><html><head><title>mock</title></head><body>mock</body></html>"
        contentType.startsWith("text/") -> "mock"
        else -> ""
    }

    /** 粗略判断是否为可读文本（替代字符占比低） */
    private fun isMostlyText(s: String): Boolean {
        val sample = s.take(4096)
        if (sample.isEmpty()) return false
        val bad = sample.count { it == '\uFFFD' || (it.code < 0x20 && it != '\n' && it != '\r' && it != '\t') }
        return bad * 50 <= sample.length
    }

    fun statusTextOf(code: Int): String = when (code) {
        200 -> "OK"
        201 -> "Created"
        202 -> "Accepted"
        204 -> "No Content"
        301 -> "Moved Permanently"
        302 -> "Found"
        304 -> "Not Modified"
        400 -> "Bad Request"
        401 -> "Unauthorized"
        403 -> "Forbidden"
        404 -> "Not Found"
        405 -> "Method Not Allowed"
        408 -> "Request Timeout"
        409 -> "Conflict"
        429 -> "Too Many Requests"
        500 -> "Internal Server Error"
        502 -> "Bad Gateway"
        503 -> "Service Unavailable"
        504 -> "Gateway Timeout"
        else -> "Mock"
    }
}
